### ISSUE TITLE
deviation vs variability

### ISSUE THREAD

**Issue by AnjaliC4** [apelonero-GladstoneInstitutes/chromVAR-Differential-Tests-forArchr#1]
Hi @apelonero-GladstoneInstitutes, thanks for implementing this with ArchR. I was trying to understand your code. In ChromVar, they use deviations for differentialdeviations and deviationScores for differentialVariability. I believe the difference is that differentialdeviations uses deviations and differentialVariability would use the bias-corrected z-scores. In your code, you use deviations from ArchR for both. What do you think about this?
inputs <- as.matrix(archrMotifMatrix@assays@data@listData$deviations)
instead of
inputs <- as.matrix(archrMotifMatrix@assays@data@listData$z)

**Comment by apelonero-GladstoneInstitutes** [comment]
Fixed! See [comment](https://github.com/GreenleafLab/ArchR/issues/340#issuecomment-1282778826) on ArchR issue #340 - thanks again.
